# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_keyboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=767)),
                ('reply', models.CharField(max_length=767)),
                ('qdate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kknouns',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('indexing', models.CharField(max_length=200)),
                ('answer', models.CharField(max_length=767)),
            ],
            options={
                'db_table': 'kknouns',
            },
        ),
        
        migrations.DeleteModel(
            name='Keyboard',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Message2',
        ),
        migrations.DeleteModel(
            name='Message3',
        ),
    ]
